# Generated by Django 5.1.1 on 2024-09-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0003_passenger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="flights",
            field=models.ManyToManyField(
                blank=True, related_name="passengers", to="airlines.flight"
            ),
        ),
    ]
